global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'localhost-ne:9100'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'Local machine'

  - job_name: 'aws_node_exporter'
    static_configs:
      - targets:
          - '3.83.83.118:9100'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'AWS instance'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - '/etc/prometheus/alerts.yml'
